name: "Frontend React Build Artefatos"

trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: variables-frontcore

jobs:
  - job: BuildAndTest
    displayName: "Publicação do artefato de React Front"

    steps:
      # Instalar Node.js
      - task: NodeTool@0
        inputs:
          versionSpec: "20.x"
        displayName: "Install Node.js"

      # Instalar dependências do projeto
      - task: CmdLine@2
        inputs:
          script: |
            npm install -g firebase-tools
            npm install
        displayName: "Instalação das Dependências"

      # Configurar a variável de ambiente
      - script: |
          echo "VITE_API_URL=$(VITE_API_URL)" >> .env
        displayName: "Configuração da variável VITE_API_URL"

      # Gerar build e realizar deploy
      - task: CmdLine@2
        inputs:
          script: |
            npm run build
            firebase deploy --token $(token-firebase) --force --only hosting
        displayName: "Gerando Artefato do Build"
