name: 'Frontend React Build Artefatos'

trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

jobs:
  - job: BuildAndTest
    displayName: 'Publicação don artefato de React Front'

    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
        displayName: 'Install Node.js'

    - task: CmdLine@2
      inputs:
        script: 'npm install'
        displayName: 'Instalação das Dependencias'

    - task: CmdLine@2
      inputs:
        script: 'npm run build'
        displayName: 'Gerando Artefato do Build'

