export * from './autenticacao.service';
export * from './carrinho_compra.service';
export * from './categoria.service';
export * from './compra_finalizada.service.js'
export * from './endereco.service';
export * from './produto_favorito.service'
export * from './produto_pedido.service';
export * from './produto.service';
export * from './unidade_medida.service';
export * from './usuario.services';
export * from './validacoes.service';
